"use client";

import { motion } from "framer-motion";
import { Activity, ArrowUpRight, Coins, CreditCard, Headphones, Music2, Sparkles, TrendingUp, UserPlus, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, LineChart, PolarGrid, PolarAngleAxis, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ChartCard from "./ChartCard";
import MetricCard from "./MetricCard";

const revenue = [{ name: "Jan 1", revenue: 2800, users: 120 }, { name: "Jan 8", revenue: 3400, users: 168 }, { name: "Jan 15", revenue: 4100, users: 201 }, { name: "Jan 22", revenue: 3900, users: 243 }, { name: "Jan 29", revenue: 5200, users: 289 }, { name: "Feb 5", revenue: 6100, users: 332 }, { name: "Feb 12", revenue: 6800, users: 396 }];
const activity = [{ name: "Mon", generations: 420, credits: 3200 }, { name: "Tue", generations: 510, credits: 3700 }, { name: "Wed", generations: 460, credits: 3400 }, { name: "Thu", generations: 680, credits: 4700 }, { name: "Fri", generations: 590, credits: 4300 }, { name: "Sat", generations: 770, credits: 5200 }, { name: "Sun", generations: 630, credits: 4800 }];
const genres = [{ subject: "Dancehall", value: 88 }, { subject: "Trap", value: 76 }, { subject: "Afrobeat", value: 68 }, { subject: "R&B", value: 62 }, { subject: "Drill", value: 54 }, { subject: "Reggae", value: 48 }];
const funnel = [{ name: "Visitors", value: 10000 }, { name: "Signups", value: 4280 }, { name: "Trials", value: 2180 }, { name: "Paid", value: 642 }];
const pieColors = ["#8b5cf6", "#3b82f6", "#22c55e", "#f59e0b"];
const tooltipStyle = { backgroundColor: "#1b1b26", border: "1px solid rgba(255,255,255,.1)", borderRadius: 8, color: "#e2e8f0", fontSize: 12 };

function PanelList({ title, items }: { title: string; items: Array<{ name: string; detail: string; value: string; color: string }> }) {
  return <section className="rounded-xl border border-white/[0.07] bg-[#181822] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-100">{title}</h2><button className="text-xs text-violet-400 hover:text-violet-300">View all</button></div><div className="space-y-4">{items.map((item) => <div key={item.name} className="flex items-center gap-3"><span className={`grid size-8 place-items-center rounded-full ${item.color} text-[11px] font-semibold text-white`}>{item.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-slate-200">{item.name}</p><p className="mt-0.5 truncate text-[11px] text-slate-600">{item.detail}</p></div><span className="text-xs font-medium text-slate-300">{item.value}</span></div>)}</div></section>;
}

export default function DashboardPage() {
  return <div className="mx-auto max-w-[1500px]">
    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35 }} className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
      <div><p className="mb-2 text-xs font-medium text-violet-400">Wednesday, February 12, 2025</p><h2 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">Good morning, Jordan <span className="text-slate-500">👋</span></h2><p className="mt-2 text-sm text-slate-500">Here&apos;s what&apos;s happening across MidiFlow today.</p></div>
      <div className="flex gap-2"><button className="rounded-lg border border-white/[0.09] px-3 py-2 text-xs font-medium text-slate-300 transition hover:bg-white/[0.04]">Last 30 days</button><button className="flex items-center gap-2 rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold text-white shadow-lg shadow-violet-600/20 transition hover:bg-violet-500"><Sparkles size={14} /> Create report</button></div>
    </motion.div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-6 sm:gap-4">
      <MetricCard label="Total users" value="24,892" change="+12.8%" icon={Users} />
      <MetricCard label="Active users" value="18,421" change="+8.4%" icon={Activity} tone="blue" />
      <MetricCard label="Paid users" value="3,842" change="+18.2%" icon={CreditCard} tone="green" />
      <MetricCard label="Monthly revenue" value="$48,290" change="+14.6%" icon={TrendingUp} tone="amber" />
      <MetricCard label="Credits used today" value="82.4K" change="+6.1%" icon={Coins} />
      <MetricCard label="Generations today" value="1,284" change="+21.3%" icon={Music2} tone="blue" />
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]">
      <ChartCard title="Revenue overview" subtitle="Gross revenue across all plans"><div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.35} /><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)" /><XAxis dataKey="name" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={(value) => `$${value / 1000}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`$${Number(value).toLocaleString()}`, "Revenue"]} /><Area type="monotone" dataKey="revenue" stroke="#8b5cf6" strokeWidth={2.5} fill="url(#revenueFill)" activeDot={{ r: 5, fill: "#a78bfa", stroke: "#181822", strokeWidth: 3 }} /></AreaChart></ResponsiveContainer></div></ChartCard>
      <ChartCard title="New users" subtitle="Weekly acquisition"><div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={revenue} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)" /><XAxis dataKey="name" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="users" fill="#3b82f6" radius={[4, 4, 0, 0]} barSize={22} /><Line type="monotone" dataKey="users" stroke="#a78bfa" strokeWidth={2} dot={false} /></ComposedChart></ResponsiveContainer></div></ChartCard>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_1fr_1fr]">
      <ChartCard title="Generation activity" subtitle="MIDI generations and credit usage"><div className="h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={activity} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)" /><XAxis dataKey="name" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis yAxisId="left" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis yAxisId="right" orientation="right" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Legend iconType="circle" wrapperStyle={{ fontSize: 11, color: "#94a3b8" }} /><Line yAxisId="left" type="monotone" dataKey="generations" name="Generations" stroke="#8b5cf6" strokeWidth={2.5} dot={false} /><Line yAxisId="right" type="monotone" dataKey="credits" name="Credits" stroke="#22c55e" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></ChartCard>
      <ChartCard title="Conversion funnel" subtitle="Trial to paid"><div className="h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={funnel} margin={{ top: 0, right: 8, left: 12, bottom: 0 }}><XAxis type="number" hide /><YAxis type="category" dataKey="name" tick={{ fill: "#94a3b8", fontSize: 11 }} axisLine={false} tickLine={false} width={58} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" radius={[0, 5, 5, 0]}>{funnel.map((entry, index) => <Cell key={entry.name} fill={pieColors[index]} fillOpacity={.85} />)}</Bar></BarChart></ResponsiveContainer></div></ChartCard>
      <ChartCard title="Top genres" subtitle="Generation share"><div className="h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><RadarChart data={genres} outerRadius="68%"><PolarGrid stroke="rgba(255,255,255,.1)" /><PolarAngleAxis dataKey="subject" tick={{ fill: "#94a3b8", fontSize: 10 }} /><Radar name="Share" dataKey="value" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={.3} /><Tooltip contentStyle={tooltipStyle} /></RadarChart></ResponsiveContainer></div></ChartCard>
    </div>
    <div className="mt-4 grid gap-4 lg:grid-cols-3">
      <PanelList title="Recent signups" items={[{ name: "Maya Thompson", detail: "maya@example.com", value: "Trial", color: "bg-violet-600" }, { name: "Andre Brown", detail: "andre@example.com", value: "Pro", color: "bg-blue-600" }, { name: "Sasha Williams", detail: "sasha@example.com", value: "Trial", color: "bg-emerald-600" }, { name: "Dario King", detail: "dario@example.com", value: "Pro", color: "bg-amber-600" }]} />
      <PanelList title="Recent payments" items={[{ name: "Andre Brown", detail: "Pro monthly", value: "$12.00", color: "bg-blue-600" }, { name: "Kiera James", detail: "Pro annual", value: "$99.00", color: "bg-violet-600" }, { name: "Dario King", detail: "Pro monthly", value: "$12.00", color: "bg-amber-600" }, { name: "Nia Campbell", detail: "Pro monthly", value: "$12.00", color: "bg-emerald-600" }]} />
      <section className="rounded-xl border border-white/[0.07] bg-[#181822] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-100">System alerts</h2><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-semibold text-emerald-400">2 healthy</span></div><div className="space-y-3"><div className="flex gap-3 rounded-lg bg-amber-500/[0.06] p-3"><span className="mt-0.5 size-2 rounded-full bg-amber-400" /><div><p className="text-xs font-medium text-slate-200">PayPal webhook latency</p><p className="mt-1 text-[11px] text-slate-500">Elevated response time · 4m ago</p></div></div><div className="flex gap-3 rounded-lg bg-blue-500/[0.06] p-3"><span className="mt-0.5 size-2 rounded-full bg-blue-400" /><div><p className="text-xs font-medium text-slate-200">New MIDI pack indexed</p><p className="mt-1 text-[11px] text-slate-500">Modern Trap Dancehall · 18m ago</p></div></div><div className="flex gap-3 rounded-lg bg-emerald-500/[0.06] p-3"><span className="mt-0.5 size-2 rounded-full bg-emerald-400" /><div><p className="text-xs font-medium text-slate-200">AI fallback recovered</p><p className="mt-1 text-[11px] text-slate-500">All models responding · 42m ago</p></div></div></div></section>
    </div>
    <div className="mt-4 grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-white/[0.07] bg-[#181822] p-5"><div className="flex items-center gap-2 text-xs text-slate-500"><Headphones size={15} className="text-violet-400" /> Support tickets</div><p className="mt-3 text-2xl font-semibold">24</p><p className="mt-2 text-xs text-amber-400">8 awaiting reply</p></div><div className="rounded-xl border border-white/[0.07] bg-[#181822] p-5"><div className="flex items-center gap-2 text-xs text-slate-500"><UserPlus size={15} className="text-blue-400" /> Referral payouts pending</div><p className="mt-3 text-2xl font-semibold">$3,842</p><p className="mt-2 text-xs text-slate-500">18 requests to review</p></div><div className="rounded-xl border border-white/[0.07] bg-[#181822] p-5"><div className="flex items-center gap-2 text-xs text-slate-500"><ArrowUpRight size={15} className="text-emerald-400" /> API usage</div><p className="mt-3 text-2xl font-semibold">68.4%</p><p className="mt-2 text-xs text-emerald-400">Within monthly limits</p></div></div>
  </div>;
}
