import { AppShell } from "@/components/app-shell";
import { GenerationComposer } from "@/features/generation/generation-composer";
import Link from "next/link";

const details: Record<string, { title: string; copy: string }> = {
  dashboard: { title: "Welcome back", copy: "Your studio is ready. Start with a thought and leave with music." },
  generate: { title: "Generate MIDI", copy: "Shape an original part with natural language and production controls." },
  "voice-to-midi": { title: "Voice to MIDI", copy: "Upload a clear hum or melody recording to transform it into editable MIDI." },
  history: { title: "Generation history", copy: "Every completed composition is stored here for quick recall." },
  downloads: { title: "Downloads", copy: "Secure MIDI exports generated by your account." },
  favorites: { title: "Favorites", copy: "Keep your most useful ideas close to hand." },
  licenses: { title: "Licenses", copy: "Review past access periods and the active state of your Pro Pass." },
  billing: { title: "Billing", copy: "Manage trial status, Pro Pass purchases, and read-only access recovery." },
  "api-keys": { title: "API keys", copy: "Create scoped developer keys and revoke them at any time." },
  settings: { title: "Settings", copy: "Control generation defaults, notifications, and privacy." },
  profile: { title: "Profile", copy: "Update your account identity and preferences." },
  support: { title: "Support", copy: "Start a ticket and follow every response in one place." },
};

export default async function WorkspacePage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  const page = details[section] ?? { title: "MidiFlow", copy: "This workspace section is not available." };
  const generator = section === "dashboard" || section === "generate";
  return <AppShell>
    <header className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-violet-300">Workspace</p><h1 className="text-3xl font-black tracking-tight">{page.title}</h1><p className="mt-2 max-w-2xl text-[#aaa3bd]">{page.copy}</p></div>{section === "billing" && <Link href="/upgrade" className="rounded-lg bg-violet-500 px-4 py-2 text-sm font-bold">Buy Pro Pass</Link>}</header>
    {generator ? <GenerationComposer /> : <section className="glass rounded-2xl p-6"><h2 className="text-lg font-bold">{page.title}</h2><p className="mt-2 text-sm text-[#aaa3bd]">Account-specific data becomes available after your Supabase project and payment credentials are configured.</p></section>}
  </AppShell>;
}
